# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436acc1ea58d7e61117d763a26797e0ee25fd0a5e6bd4d49f10cd104aedf4a7af26249e52a8cc299cfccdf32c1a6e6043ecc2a49f83e333f4cbf965247dac710

test:
  secret_key_base: 683251f291076884df4062d648aa7f1025fbaaedeab947a610f8c991f55544344e735b181c6b358a31c61dd5e54446cdbbf0fcefd307c68e7f9363f8c25f60c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
